version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tourism_agency
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQLUSER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLPASSWORD}
