version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tourism_agency
    ports:
      - "8080:8080"
    environment:
      MYSQL_PUBLIC_URL: ${MYSQL_PUBLIC_URL}
      MYSQLUSER: ${MYSQLUSER}
      MYSQLPASSWORD: ${MYSQLPASSWORD}
