spring:
  application:
    name: tourism-agency

  datasource:
    #url: jdbc:mysql://database:3306/tourism-db
    url: jdbc:mysql://localhost:3306/tourism_agency_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate.format_sql: true




